"""add audit logs security logs role permissions point of sale tables for super admin system

Revision ID: 5c57a60106d5
Revises: c98a5b5e0fd5
Create Date: 2026-04-22 23:35:39.984319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c57a60106d5'
down_revision: Union[str, None] = '005_add_performance_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_module'), 'role_permissions', ['module'], unique=False)
    op.create_index(op.f('ix_role_permissions_role'), 'role_permissions', ['role'], unique=False)
    op.create_index('ix_role_permissions_role_module', 'role_permissions', ['role', 'module'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'EXPORT', 'IMPORT', 'APPROVE', 'REJECT', 'SUSPEND', 'ACTIVATE', 'IMPERSONATE', 'PASSWORD_CHANGE', 'ROLE_CHANGE', 'SETTINGS_CHANGE', 'VIEW', 'SEARCH', 'DOWNLOAD', 'SHARE', 'COMMENT', 'RATE', 'PAYMENT', 'REFUND', 'CANCEL', 'CONFIRM', 'COMPLETE', name='auditaction'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changes_summary', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_action_entity_created', 'audit_logs', ['action', 'entity_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_created_at_desc', 'audit_logs', [sa.text('created_at DESC')], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index('ix_audit_logs_user_action', 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_table('points_of_sale',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.String(length=10), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_points_of_sale_active', 'points_of_sale', ['is_active'], unique=False)
    op.create_index('ix_points_of_sale_assigned', 'points_of_sale', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_points_of_sale_code'), 'points_of_sale', ['code'], unique=True)
    op.create_table('security_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.Enum('LOGIN_SUCCESS', 'LOGIN_FAILURE', 'LOGOUT', 'PASSWORD_CHANGE', 'PASSWORD_RESET_REQUEST', 'PASSWORD_RESET_COMPLETE', 'TOKEN_REFRESH', 'TOKEN_REVOKED', 'ACCESS_DENIED', 'RATE_LIMIT_HIT', 'SUSPICIOUS_ACTIVITY', 'ACCOUNT_LOCKED', 'ACCOUNT_UNLOCKED', 'MFA_ENABLED', 'MFA_DISABLED', 'MFA_VERIFICATION', 'SESSION_EXPIRED', 'FORCE_LOGOUT', name='securityaction'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('token_id', sa.String(length=100), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_logs_action'), 'security_logs', ['action'], unique=False)
    op.create_index(op.f('ix_security_logs_created_at'), 'security_logs', ['created_at'], unique=False)
    op.create_index('ix_security_logs_created_at_desc', 'security_logs', [sa.text('created_at DESC')], unique=False)
    op.create_index(op.f('ix_security_logs_device_fingerprint'), 'security_logs', ['device_fingerprint'], unique=False)
    op.create_index('ix_security_logs_failed_logins', 'security_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_security_logs_ip_action', 'security_logs', ['ip_address', 'action'], unique=False)
    op.create_index(op.f('ix_security_logs_ip_address'), 'security_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_security_logs_session_id'), 'security_logs', ['session_id'], unique=False)
    op.create_index('ix_security_logs_suspicious', 'security_logs', ['severity', 'created_at'], unique=False)
    op.create_index('ix_security_logs_user_action', 'security_logs', ['user_id', 'action'], unique=False)
    op.create_index(op.f('ix_security_logs_user_email'), 'security_logs', ['user_email'], unique=False)
    op.create_index(op.f('ix_security_logs_user_id'), 'security_logs', ['user_id'], unique=False)
    op.drop_index('idx_boat_location', table_name='boat_equipment')
    op.drop_index('idx_boat_type', table_name='boat_equipment')
    op.drop_index('idx_boat_vendor', table_name='boat_equipment')
    op.drop_table('boat_equipment')
    op.create_index('idx_blog_author', 'blog_posts', ['author_id'], unique=False)
    op.create_index('idx_blog_featured', 'blog_posts', ['is_featured', 'status'], unique=False)
    op.create_index('idx_blog_published', 'blog_posts', ['published_at'], unique=False)
    op.add_column('bookings', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.create_index('idx_booking_checkin', 'bookings', ['check_in'], unique=False)
    op.create_index('idx_booking_tour', 'bookings', ['tour_id'], unique=False)
    op.create_index('idx_conv_active', 'conversations', ['is_active', 'last_message_at'], unique=False)
    op.create_index('idx_destination_featured', 'destinations', ['is_featured', 'is_active'], unique=False)
    op.drop_index('idx_flight_airline', table_name='flights')
    op.drop_index('idx_flight_number', table_name='flights')
    op.drop_index('idx_flight_route', table_name='flights')
    op.create_index('idx_message_read', 'messages', ['read_at'], unique=False)
    op.drop_index('idx_pricing_active', table_name='pricing_rules')
    op.drop_index('idx_pricing_dates', table_name='pricing_rules')
    op.drop_index('idx_pricing_service', table_name='pricing_rules')
    op.alter_column('properties', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('idx_property_active', table_name='properties')
    op.drop_index('idx_property_region', table_name='properties')
    op.drop_index('idx_property_vendor', table_name='properties')
    op.create_index('idx_property_featured', 'properties', ['is_featured', 'is_active'], unique=False)
    op.create_index('idx_property_location', 'properties', ['region', 'city'], unique=False)
    op.create_index('idx_property_price', 'properties', ['base_price'], unique=False)
    op.drop_column('properties', 'seo_slug')
    op.drop_column('properties', 'total_bookings')
    op.add_column('reviews', sa.Column('booking_id', sa.UUID(), nullable=True))
    op.add_column('reviews', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('idx_review_approved', 'reviews', ['is_approved'], unique=False)
    op.create_index('idx_review_booking', 'reviews', ['booking_id'], unique=False)
    op.create_foreign_key(None, 'reviews', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.add_column('rooms', sa.Column('max_guests', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('beds', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('cleaning_fee', sa.Float(), nullable=True))
    op.alter_column('rooms', 'bed_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_column('rooms', 'square_meters')
    op.drop_column('rooms', 'currency')
    op.drop_column('rooms', 'amenities')
    op.drop_column('rooms', 'bed_count')
    op.drop_column('rooms', 'base_price')
    op.drop_column('rooms', 'bath_count')
    op.drop_column('rooms', 'slug')
    op.drop_column('rooms', 'room_type')
    op.drop_column('rooms', 'is_featured')
    op.drop_column('rooms', 'max_occupancy')
    op.create_index('idx_tour_featured', 'tours', ['is_featured', 'is_active'], unique=False)
    op.create_index('idx_tour_price', 'tours', ['price'], unique=False)
    op.drop_index('idx_transport_service', table_name='transportation')
    op.drop_index('idx_transport_vendor', table_name='transportation')
    op.add_column('users', sa.Column('email_verification_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_verification_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(), nullable=True))
    op.drop_index('idx_vehicle_active', table_name='vehicles')
    op.drop_index('idx_vehicle_location', table_name='vehicles')
    op.drop_index('idx_vehicle_type', table_name='vehicles')
    op.drop_index('idx_vehicle_vendor', table_name='vehicles')
    op.add_column('vendors', sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'REJECTED', name='vendorstatus'), server_default='PENDING', nullable=True))
    op.drop_index('idx_vendor_business_type', table_name='vendors')
    op.drop_index('idx_vendor_rating', table_name='vendors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_vendor_rating', 'vendors', ['rating'], unique=False)
    op.create_index('idx_vendor_business_type', 'vendors', ['business_type'], unique=False)
    op.drop_column('vendors', 'status')
    op.create_index('idx_vehicle_vendor', 'vehicles', ['vendor_id'], unique=False)
    op.create_index('idx_vehicle_type', 'vehicles', ['vehicle_type'], unique=False)
    op.create_index('idx_vehicle_location', 'vehicles', ['location'], unique=False)
    op.create_index('idx_vehicle_active', 'vehicles', ['is_active'], unique=False)
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'email_verification_expires')
    op.drop_column('users', 'email_verification_token')
    op.create_index('idx_transport_vendor', 'transportation', ['vendor_id'], unique=False)
    op.create_index('idx_transport_service', 'transportation', ['service_type'], unique=False)
    op.drop_index('idx_tour_price', table_name='tours')
    op.drop_index('idx_tour_featured', table_name='tours')
    op.add_column('rooms', sa.Column('max_occupancy', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('room_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('slug', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('rooms', sa.Column('bath_count', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('base_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('bed_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('amenities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('square_meters', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('rooms', 'bed_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('rooms', 'cleaning_fee')
    op.drop_column('rooms', 'beds')
    op.drop_column('rooms', 'max_guests')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_index('idx_review_booking', table_name='reviews')
    op.drop_index('idx_review_approved', table_name='reviews')
    op.drop_column('reviews', 'updated_at')
    op.drop_column('reviews', 'booking_id')
    op.add_column('properties', sa.Column('total_bookings', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('seo_slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index('idx_property_price', table_name='properties')
    op.drop_index('idx_property_location', table_name='properties')
    op.drop_index('idx_property_featured', table_name='properties')
    op.create_index('idx_property_vendor', 'properties', ['vendor_id'], unique=False)
    op.create_index('idx_property_region', 'properties', ['region'], unique=False)
    op.create_index('idx_property_active', 'properties', ['is_active'], unique=False)
    op.alter_column('properties', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index('idx_pricing_service', 'pricing_rules', ['service_type', 'service_id'], unique=False)
    op.create_index('idx_pricing_dates', 'pricing_rules', ['date_from', 'date_to'], unique=False)
    op.create_index('idx_pricing_active', 'pricing_rules', ['is_active'], unique=False)
    op.drop_index('idx_message_read', table_name='messages')
    op.create_index('idx_flight_route', 'flights', ['route_type'], unique=False)
    op.create_index('idx_flight_number', 'flights', ['flight_number'], unique=False)
    op.create_index('idx_flight_airline', 'flights', ['airline'], unique=False)
    op.drop_index('idx_destination_featured', table_name='destinations')
    op.drop_index('idx_conv_active', table_name='conversations')
    op.drop_index('idx_booking_tour', table_name='bookings')
    op.drop_index('idx_booking_checkin', table_name='bookings')
    op.drop_column('bookings', 'cancellation_reason')
    op.drop_column('bookings', 'cancelled_at')
    op.drop_column('bookings', 'confirmed_at')
    op.drop_index('idx_blog_published', table_name='blog_posts')
    op.drop_index('idx_blog_featured', table_name='blog_posts')
    op.drop_index('idx_blog_author', table_name='blog_posts')
    op.create_table('boat_equipment',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('equipment_type', postgresql.ENUM('BOAT', 'JET_SKI', 'KAYAK', 'PADDLEBOARD', 'EQUIPMENT', name='boattype'), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('length_foot', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('images', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('price_per_hour', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('price_per_day', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('price_per_week', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('requires_license', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('license_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('operating_area', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_reviews', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_rentals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name='boat_equipment_vendor_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='boat_equipment_pkey')
    )
    op.create_index('idx_boat_vendor', 'boat_equipment', ['vendor_id'], unique=False)
    op.create_index('idx_boat_type', 'boat_equipment', ['equipment_type'], unique=False)
    op.create_index('idx_boat_location', 'boat_equipment', ['location'], unique=False)
    op.drop_index(op.f('ix_security_logs_user_id'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_user_email'), table_name='security_logs')
    op.drop_index('ix_security_logs_user_action', table_name='security_logs')
    op.drop_index('ix_security_logs_suspicious', table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_session_id'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_ip_address'), table_name='security_logs')
    op.drop_index('ix_security_logs_ip_action', table_name='security_logs')
    op.drop_index('ix_security_logs_failed_logins', table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_device_fingerprint'), table_name='security_logs')
    op.drop_index('ix_security_logs_created_at_desc', table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_created_at'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_action'), table_name='security_logs')
    op.drop_table('security_logs')
    op.drop_index(op.f('ix_points_of_sale_code'), table_name='points_of_sale')
    op.drop_index('ix_points_of_sale_assigned', table_name='points_of_sale')
    op.drop_index('ix_points_of_sale_active', table_name='points_of_sale')
    op.drop_table('points_of_sale')
    op.drop_index('ix_audit_logs_user_action', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at_desc', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_entity_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_role_permissions_role_module', table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_role'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_module'), table_name='role_permissions')
    op.drop_table('role_permissions')
    # ### end Alembic commands ###