"""add_content_models

Revision ID: 95526b2e75d5
Revises: 013
Create Date: 2026-06-26 03:45:51.981533

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95526b2e75d5"
down_revision: str | None = "013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "static_pages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("template", sa.String(length=100), nullable=True),
        sa.Column("meta_title", sa.String(length=70), nullable=True),
        sa.Column("meta_description", sa.String(length=160), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("show_in_footer", sa.Boolean(), nullable=False),
        sa.Column("show_in_header", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_static_pages_active", "static_pages", ["is_active"], unique=False)
    op.create_index("idx_static_pages_slug", "static_pages", ["slug"], unique=False)
    op.create_index("idx_static_pages_sort", "static_pages", ["sort_order"], unique=False)
    op.create_index(op.f("ix_static_pages_slug"), "static_pages", ["slug"], unique=True)
    op.create_table(
        "media_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("original_name", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("thumbnail_url", sa.String(length=1000), nullable=True),
        sa.Column("alt_text", sa.String(length=500), nullable=True),
        sa.Column("folder", sa.String(length=100), nullable=True),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column("used_in", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("filename"),
    )
    op.create_index("idx_media_files_folder", "media_files", ["folder"], unique=False)
    op.create_index("idx_media_files_mime", "media_files", ["mime_type"], unique=False)
    op.create_index("idx_media_files_uploaded_by", "media_files", ["uploaded_by"], unique=False)
    op.create_table(
        "seo_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("site_title_template", sa.String(length=200), nullable=False),
        sa.Column("default_meta_title", sa.String(length=200), nullable=False),
        sa.Column("default_meta_description", sa.Text(), nullable=False),
        sa.Column("default_meta_keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("google_site_verification", sa.String(length=255), nullable=True),
        sa.Column("robots_txt", sa.Text(), nullable=False),
        sa.Column("sitemap_enabled", sa.Boolean(), nullable=False),
        sa.Column("structured_data_enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index("idx_blog_fts", table_name="blog_posts", postgresql_using="gin")
    op.create_index(
        "idx_blog_fts",
        "blog_posts",
        [
            sa.text(
                "to_tsvector('spanish', COALESCE(title, '') || ' ' || COALESCE(content, '') || ' ' || COALESCE(excerpt, ''))"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("idx_blog_created_at", "blog_posts", ["created_at"], unique=False)
    op.create_index(
        "idx_blog_status_published", "blog_posts", ["status", "published_at"], unique=False
    )
    op.create_index("idx_boat_created_at", "boats", ["created_at"], unique=False)
    op.create_index("idx_boat_is_active", "boats", ["is_active"], unique=False)
    op.create_index("idx_boat_is_available", "boats", ["is_available"], unique=False)
    op.create_index("idx_booking_check_out", "bookings", ["check_out"], unique=False)
    op.create_index(
        "idx_booking_property_checkin", "bookings", ["property_id", "check_in"], unique=False
    )
    op.create_index(
        "idx_booking_status_created", "bookings", ["status", "created_at"], unique=False
    )
    op.create_index("idx_booking_user_status", "bookings", ["user_id", "status"], unique=False)
    op.drop_index("idx_destination_name_trgm", table_name="destinations", postgresql_using="gin")
    op.drop_index("idx_destination_region_trgm", table_name="destinations", postgresql_using="gin")
    op.create_index("idx_destination_created_at", "destinations", ["created_at"], unique=False)
    op.create_index("idx_destination_is_active", "destinations", ["is_active"], unique=False)
    op.create_index("idx_destination_is_featured", "destinations", ["is_featured"], unique=False)
    op.create_index(
        "idx_flight_active_departure", "flights", ["is_active", "departure_time"], unique=False
    )
    op.create_index("idx_flight_departure", "flights", ["departure_time"], unique=False)
    op.create_index("idx_flight_destination", "flights", ["destination_airport"], unique=False)
    op.drop_index("idx_property_city_trgm", table_name="properties", postgresql_using="gin")
    op.drop_index("idx_property_region_trgm", table_name="properties", postgresql_using="gin")
    op.drop_index("idx_property_fts", table_name="properties", postgresql_using="gin")
    op.create_index(
        "idx_property_fts",
        "properties",
        [
            sa.text(
                "to_tsvector('spanish', COALESCE(name, '') || ' ' || COALESCE(short_description, '') || ' ' || COALESCE(description, '') || ' ' || COALESCE(city, '') || ' ' || COALESCE(region, ''))"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_property_active_created", "properties", ["is_active", "created_at"], unique=False
    )
    op.create_index("idx_property_created_at", "properties", ["created_at"], unique=False)
    op.create_index("idx_property_is_active", "properties", ["is_active"], unique=False)
    op.create_index("idx_property_is_featured", "properties", ["is_featured"], unique=False)
    op.create_index("idx_property_vendor", "properties", ["vendor_id"], unique=False)
    op.create_index(
        "idx_property_vendor_active", "properties", ["vendor_id", "is_active"], unique=False
    )
    op.drop_index("idx_tour_location_trgm", table_name="tours", postgresql_using="gin")
    op.drop_index("idx_tour_fts", table_name="tours", postgresql_using="gin")
    op.create_index(
        "idx_tour_fts",
        "tours",
        [
            sa.text(
                "to_tsvector('spanish', COALESCE(name, '') || ' ' || COALESCE(description, '') || ' ' || COALESCE(location, ''))"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("idx_tour_active_created", "tours", ["is_active", "created_at"], unique=False)
    op.create_index("idx_tour_created_at", "tours", ["created_at"], unique=False)
    op.create_index("idx_transport_created_at", "transportation", ["created_at"], unique=False)
    op.create_index("idx_transport_is_active", "transportation", ["is_active"], unique=False)
    op.create_index("idx_transport_is_available", "transportation", ["is_available"], unique=False)
    op.create_index("idx_vehicle_created_at", "vehicles", ["created_at"], unique=False)
    op.create_index("idx_vehicle_is_active", "vehicles", ["is_active"], unique=False)
    op.create_index("idx_vehicle_is_available", "vehicles", ["is_available"], unique=False)
    op.create_index("idx_vendor_active", "vendors", ["is_active"], unique=False)
    op.create_index("idx_vendor_business_type", "vendors", ["business_type"], unique=False)
    op.create_index("idx_vendor_created_at", "vendors", ["created_at"], unique=False)
    op.create_index("idx_vendor_slug", "vendors", ["business_slug"], unique=False)
    op.create_index("idx_vendor_user", "vendors", ["user_id"], unique=False)
    op.create_index("idx_vendor_verified", "vendors", ["is_verified"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_vendor_verified", table_name="vendors")
    op.drop_index("idx_vendor_user", table_name="vendors")
    op.drop_index("idx_vendor_slug", table_name="vendors")
    op.drop_index("idx_vendor_created_at", table_name="vendors")
    op.drop_index("idx_vendor_business_type", table_name="vendors")
    op.drop_index("idx_vendor_active", table_name="vendors")
    op.drop_index("idx_vehicle_is_available", table_name="vehicles")
    op.drop_index("idx_vehicle_is_active", table_name="vehicles")
    op.drop_index("idx_vehicle_created_at", table_name="vehicles")
    op.drop_index("idx_transport_is_available", table_name="transportation")
    op.drop_index("idx_transport_is_active", table_name="transportation")
    op.drop_index("idx_transport_created_at", table_name="transportation")
    op.drop_index("idx_tour_created_at", table_name="tours")
    op.drop_index("idx_tour_active_created", table_name="tours")
    op.drop_index("idx_tour_fts", table_name="tours", postgresql_using="gin")
    op.create_index(
        "idx_tour_fts",
        "tours",
        [
            sa.text(
                "to_tsvector('spanish'::regconfig, (((COALESCE(name, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || COALESCE(location, ''::character varying)::text)"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_tour_location_trgm", "tours", ["location"], unique=False, postgresql_using="gin"
    )
    op.drop_index("idx_property_vendor_active", table_name="properties")
    op.drop_index("idx_property_vendor", table_name="properties")
    op.drop_index("idx_property_is_featured", table_name="properties")
    op.drop_index("idx_property_is_active", table_name="properties")
    op.drop_index("idx_property_created_at", table_name="properties")
    op.drop_index("idx_property_active_created", table_name="properties")
    op.drop_index("idx_property_fts", table_name="properties", postgresql_using="gin")
    op.create_index(
        "idx_property_fts",
        "properties",
        [
            sa.text(
                "to_tsvector('spanish'::regconfig, (((((((COALESCE(name, ''::character varying)::text || ' '::text) || COALESCE(short_description, ''::character varying)::text) || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || COALESCE(city, ''::character varying)::text) || ' '::text) || COALESCE(region, ''::character varying)::text)"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_property_region_trgm", "properties", ["region"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "idx_property_city_trgm", "properties", ["city"], unique=False, postgresql_using="gin"
    )
    op.drop_index("idx_flight_destination", table_name="flights")
    op.drop_index("idx_flight_departure", table_name="flights")
    op.drop_index("idx_flight_active_departure", table_name="flights")
    op.drop_index("idx_destination_is_featured", table_name="destinations")
    op.drop_index("idx_destination_is_active", table_name="destinations")
    op.drop_index("idx_destination_created_at", table_name="destinations")
    op.create_index(
        "idx_destination_region_trgm",
        "destinations",
        ["region"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_destination_name_trgm", "destinations", ["name"], unique=False, postgresql_using="gin"
    )
    op.drop_index("idx_booking_user_status", table_name="bookings")
    op.drop_index("idx_booking_status_created", table_name="bookings")
    op.drop_index("idx_booking_property_checkin", table_name="bookings")
    op.drop_index("idx_booking_check_out", table_name="bookings")
    op.drop_index("idx_boat_is_available", table_name="boats")
    op.drop_index("idx_boat_is_active", table_name="boats")
    op.drop_index("idx_boat_created_at", table_name="boats")
    op.drop_index("idx_blog_status_published", table_name="blog_posts")
    op.drop_index("idx_blog_created_at", table_name="blog_posts")
    op.drop_index("idx_blog_fts", table_name="blog_posts", postgresql_using="gin")
    op.create_index(
        "idx_blog_fts",
        "blog_posts",
        [
            sa.text(
                "to_tsvector('spanish'::regconfig, (((COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(content, ''::text)) || ' '::text) || COALESCE(excerpt, ''::text))"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_table("seo_settings")
    op.drop_index("idx_media_files_uploaded_by", table_name="media_files")
    op.drop_index("idx_media_files_mime", table_name="media_files")
    op.drop_index("idx_media_files_folder", table_name="media_files")
    op.drop_table("media_files")
    op.drop_index(op.f("ix_static_pages_slug"), table_name="static_pages")
    op.drop_index("idx_static_pages_sort", table_name="static_pages")
    op.drop_index("idx_static_pages_slug", table_name="static_pages")
    op.drop_index("idx_static_pages_active", table_name="static_pages")
    op.drop_table("static_pages")
    # ### end Alembic commands ###
